import type {NextPage} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {useRouter} from 'next/router';
import {useQuery} from '@tanstack/react-query';
import {plainCard} from '../../assets/images/images';
import {slugify} from '../../helpers';
import {getWebpages} from '../../queryfns';

interface CardProps {
  company_name: string;
  image_url: string;
}

function Card({company_name, image_url}: CardProps) {
  return (
    <Link href={`/companies/${slugify(company_name)}`}>
      <a className="flex flex-col gap-5 py-14">
        <h2 className="text-md font-medium text-grey">{company_name}</h2>
        <div className="relative">
          {image_url ? (
            <Image
              alt=""
              src={image_url}
              width={620}
              height={411}
              layout="responsive"
              objectFit="cover"
              placeholder="blur"
              blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xg8AAnMBeJQW2OIAAAAASUVORK5CYII="
              className="rounded-2xl"
            />
          ) : (
            <Image
              alt=""
              src={plainCard}
              width={620}
              height={411}
              layout="responsive"
              placeholder="blur"
              objectFit="cover"
              blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xg8AAnMBeJQW2OIAAAAASUVORK5CYII="
              className="rounded-2xl"
            />
          )}
        </div>
      </a>
    </Link>
  );
}

interface Pages {
  page_name: string;
  attributes: {
    pages: string[];
    name: string;
  };
  company_name: string;
  image_url: string;
}

const IndividualWebpages: NextPage = () => {
  const router = useRouter();

  const {data: webpages} = useQuery(['webpages'], getWebpages);

  const pagesArray = webpages?.data?.map(
    (page: Pages) => page.attributes.pages,
  );

  const flattenedPages = pagesArray?.flat();

  const specificPages = flattenedPages?.filter(
    (page: Pages) => slugify(page.page_name) === router.query.id,
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="py-16">
        <h1 className="text-xl font-medium text-grey">
          {specificPages?.[0]?.page_name}
        </h1>
      </section>

      <section>
        <div className="grid grid-cols-2 gap-x-12 px-3">
          {specificPages?.map((page: Pages, index: number) => (
            <Card
              key={index}
              company_name={page.company_name}
              image_url={page.image_url}
            />
          ))}
        </div>
      </section>
    </>
  );
};

export default IndividualWebpages;
