import type {GetStaticProps, NextPage} from 'next';
import Head from 'next/head';
import {dehydrate, QueryClient, useQuery} from '@tanstack/react-query';
import {getCompanies} from '../../queryfns';
import {CompanyCard, HeadingOne} from '../../components';

const Companies: NextPage = () => {
  const {data: companies} = useQuery(['companies'], getCompanies);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadingOne text="All companies" />

      <section>
        <CompanyCard companies={companies?.data} />
      </section>
    </>
  );
};

export default Companies;

export const getStaticProps: GetStaticProps = async () => {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(['companies'], getCompanies);
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};
