import type {NextPage} from 'next';
import Head from 'next/head';
import CompanyCard from '../components/CompanyCard';
import {useCompanies} from '../hooks';

const Pages: NextPage = () => {
  const {data: companies} = useCompanies();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="mx-auto max-w-[922px] py-20 text-center">
        <h1 className="text-2xl font-bold text-grey">
          Find your favorite sites in one place, then learn from the greats.
        </h1>
        <p className="mt-6 mb-2 text-md font-medium text-body">
          We track each of these sites and update our collection regularly to
          include the latest designs.
        </p>
        <p className="text-md font-medium text-blue">*No account needed</p>
      </section>

      <section>
        <CompanyCard companies={companies?.data} />
      </section>
    </>
  );
};

export default Pages;
